import "server-only";

import robots from "@/app/robots";
import { getIndexableProducts, type IndexableProduct } from "@/lib/inventory/repository";
import { SERVICE_LOCATIONS } from "@/lib/content/locations";
import { GUIDES } from "@/lib/content/guides";
import { auditLocations, indexableLocations, type LocationIssue } from "@/lib/seo/location-quality";
import { localBusinessSchema } from "@/lib/seo/jsonld";
import { buildSitemap, SITEMAP_URL_LIMIT, type SitemapReport } from "@/lib/seo/sitemap";
import { isIndexNowConfigured } from "@/lib/seo/indexnow";
import { SITE_URL, siteConfig } from "@/lib/site-config";

/**
 * The daily self-check.
 *
 * Deliberately introspective: it inspects this application's own data and its
 * own generators rather than crawling the live site. Everything that can go
 * wrong in the ways this system fails — a location record that slipped below the
 * content bar, a duplicate slug, a product published without a slug or a photo,
 * the canonical domain reverting to localhost, the business phone drifting off
 * the LocalBusiness node — is visible from inside the process, for free, without
 * a single outbound request.
 *
 * What it does not do is fetch pages. A daily crawl of the whole catalogue to
 * confirm pages that were generated by the same code that just built the
 * sitemap is a lot of traffic to learn nothing.
 */

/** The number customers are given. Anything else on the LocalBusiness node is a bug. */
const PUBLIC_PHONE_E164 = "+19735199717";

/** The Twilio sender. Publishing this as the business phone breaks NAP matching. */
const TWILIO_SENDER_E164 = "+15707500622";

export type CheckStatus = "pass" | "warn" | "fail";

export interface HealthCheck {
  name: string;
  status: CheckStatus;
  detail: string;
}

export interface SeoHealthReport {
  ok: boolean;
  checkedAt: string;
  canonicalOrigin: string;
  status: CheckStatus;
  checks: HealthCheck[];
  sitemap: SitemapReport;
  locations: {
    total: number;
    indexable: number;
    issues: LocationIssue[];
  };
  inventory: {
    published: number;
    available: number;
    sold: number;
    missingImages: number;
    missingDescriptions: number;
  };
  indexNow: { configured: boolean };
}

function worst(statuses: CheckStatus[]): CheckStatus {
  if (statuses.includes("fail")) return "fail";
  if (statuses.includes("warn")) return "warn";
  return "pass";
}

function inventorySummary(products: IndexableProduct[]) {
  return {
    published: products.length,
    available: products.filter((product) => product.status === "available").length,
    sold: products.filter((product) => product.status === "sold").length,
    missingImages: products.filter((product) => !product.hasImage).length,
    missingDescriptions: products.filter((product) => !product.hasDescription).length,
  };
}

export async function runSeoHealthCheck(): Promise<SeoHealthReport> {
  const checks: HealthCheck[] = [];
  const push = (name: string, status: CheckStatus, detail: string) =>
    checks.push({ name, status, detail });

  // --- Canonical domain -----------------------------------------------------
  const configuredOrigin = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (!configuredOrigin) {
    push(
      "canonical-domain",
      "fail",
      "NEXT_PUBLIC_SITE_URL is not set, so canonicals point at localhost and robots.txt disallows all crawling.",
    );
  } else if (!configuredOrigin.startsWith("https://")) {
    push("canonical-domain", "fail", `NEXT_PUBLIC_SITE_URL is "${configuredOrigin}" — it must be an https origin.`);
  } else if (configuredOrigin.endsWith("/")) {
    push("canonical-domain", "warn", "NEXT_PUBLIC_SITE_URL has a trailing slash; it is stripped, but set it without one.");
  } else {
    push("canonical-domain", "pass", `Canonical origin is ${SITE_URL}.`);
  }

  // --- robots.txt -----------------------------------------------------------
  try {
    const policy = robots();
    const rules = Array.isArray(policy.rules) ? policy.rules : [policy.rules];
    const disallowed = rules.flatMap((rule) => {
      const value = rule?.disallow;
      return Array.isArray(value) ? value : value ? [value] : [];
    });

    if (disallowed.includes("/")) {
      push("robots", "fail", "robots.txt disallows the whole site — the canonical domain is not configured.");
    } else if (disallowed.some((path) => path.startsWith("/_next"))) {
      // Blocking the build output blocks the CSS and JS Google renders with.
      push("robots", "fail", "robots.txt disallows /_next, which blocks the CSS and JavaScript crawlers need to render pages.");
    } else if (!policy.sitemap) {
      push("robots", "warn", "robots.txt does not reference a sitemap.");
    } else {
      push("robots", "pass", `robots.txt generated, referencing ${String(policy.sitemap)}.`);
    }
  } catch (error) {
    push("robots", "fail", `robots.txt generation threw: ${error instanceof Error ? error.message : "unknown error"}`);
  }

  // --- Sitemap --------------------------------------------------------------
  let sitemap: SitemapReport = {
    total: 0,
    counts: { static: 0, categories: 0, campaigns: 0, locations: 0, guides: 0, products: 0 },
    needsSharding: false,
    duplicates: [],
  };
  try {
    sitemap = (await buildSitemap()).report;
    if (sitemap.duplicates.length > 0) {
      push("sitemap", "fail", `Sitemap contains ${sitemap.duplicates.length} duplicate URL(s): ${sitemap.duplicates.slice(0, 5).join(", ")}`);
    } else if (sitemap.needsSharding) {
      push("sitemap", "warn", `Sitemap holds ${sitemap.total} URLs, past the ${SITEMAP_URL_LIMIT} per-file limit. Split it with generateSitemaps.`);
    } else if (sitemap.total === 0) {
      push("sitemap", "fail", "Sitemap generated zero URLs.");
    } else {
      push("sitemap", "pass", `Sitemap generated ${sitemap.total} URLs.`);
    }
  } catch (error) {
    push("sitemap", "fail", `Sitemap generation threw: ${error instanceof Error ? error.message : "unknown error"}`);
  }

  // --- Location quality -----------------------------------------------------
  const locationIssues = auditLocations();
  const errors = locationIssues.filter((issue) => issue.severity === "error");
  const warnings = locationIssues.filter((issue) => issue.severity === "warning");
  const indexable = indexableLocations();

  if (errors.length > 0) {
    push(
      "locations",
      "fail",
      `${errors.length} location record(s) fail the content bar and are excluded from the index: ${[...new Set(errors.map((issue) => issue.slug))].join(", ")}`,
    );
  } else if (warnings.length > 0) {
    push("locations", "warn", `${warnings.length} location warning(s) — see the issues list.`);
  } else {
    push("locations", "pass", `${indexable.length} of ${SERVICE_LOCATIONS.length} service areas clear the content bar.`);
  }

  // --- Business facts in structured data ------------------------------------
  const business = localBusinessSchema(indexable) as Record<string, unknown>;
  const telephone = String(business.telephone ?? "");
  const address = business.address as Record<string, unknown> | undefined;

  if (telephone === TWILIO_SENDER_E164) {
    push("nap-phone", "fail", "LocalBusiness telephone is the Twilio sending number. It must be the public business line.");
  } else if (telephone !== PUBLIC_PHONE_E164) {
    push("nap-phone", "fail", `LocalBusiness telephone is "${telephone}", expected ${PUBLIC_PHONE_E164}. Check NEXT_PUBLIC_BUSINESS_PHONE.`);
  } else {
    push("nap-phone", "pass", `LocalBusiness telephone is ${telephone}.`);
  }

  const addressComplete =
    Boolean(address?.streetAddress) &&
    Boolean(address?.addressLocality) &&
    Boolean(address?.addressRegion) &&
    Boolean(address?.postalCode);
  push(
    "nap-address",
    addressComplete ? "pass" : "fail",
    addressComplete
      ? `LocalBusiness address is ${siteConfig.address.oneLine} ${siteConfig.address.postalCode}.`
      : "LocalBusiness address is incomplete.",
  );

  // --- Inventory records ----------------------------------------------------
  const products = await getIndexableProducts();
  const inventory = inventorySummary(products);
  const slugless = products.filter((product) => !product.slug.trim());

  if (slugless.length > 0) {
    push("inventory-slugs", "fail", `${slugless.length} published appliance(s) have no slug, so their URLs cannot be generated.`);
  } else if (products.length === 0) {
    push("inventory-slugs", "warn", "No published inventory — product URLs are absent from the sitemap.");
  } else {
    push("inventory-slugs", "pass", `${products.length} published appliance URLs.`);
  }

  const duplicateSlugs = products
    .map((product) => product.slug)
    .filter((slug, index, all) => all.indexOf(slug) !== index);
  push(
    "inventory-duplicate-slugs",
    duplicateSlugs.length > 0 ? "fail" : "pass",
    duplicateSlugs.length > 0
      ? `Duplicate product slugs: ${[...new Set(duplicateSlugs)].slice(0, 5).join(", ")}`
      : "No duplicate product slugs.",
  );

  if (inventory.missingImages > 0) {
    push(
      "inventory-completeness",
      "warn",
      `${inventory.missingImages} published appliance(s) have no photograph and ${inventory.missingDescriptions} have no description — those pages index thin and cannot carry Product image data.`,
    );
  } else {
    push("inventory-completeness", "pass", "Every published appliance has at least one photograph.");
  }

  // --- Guides ---------------------------------------------------------------
  const staleGuides = GUIDES.filter((guide) => {
    const updated = Date.parse(guide.updated);
    if (Number.isNaN(updated)) return true;
    return Date.now() - updated > 365 * 24 * 60 * 60 * 1000;
  });
  push(
    "guides",
    staleGuides.length > 0 ? "warn" : "pass",
    staleGuides.length > 0
      ? `${staleGuides.length} guide(s) not reviewed in over a year: ${staleGuides.map((guide) => guide.slug).join(", ")}`
      : `${GUIDES.length} guides, all reviewed within the last year.`,
  );

  // --- Search Console -------------------------------------------------------
  push(
    "search-console",
    process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION?.trim() ? "pass" : "warn",
    process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION?.trim()
      ? "Search Console verification tag is configured."
      : "NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION is not set. Domain-level DNS verification does not need it; the HTML tag method does.",
  );

  const status = worst(checks.map((check) => check.status));

  return {
    ok: status !== "fail",
    checkedAt: new Date().toISOString(),
    canonicalOrigin: SITE_URL,
    status,
    checks,
    sitemap,
    locations: {
      total: SERVICE_LOCATIONS.length,
      indexable: indexable.length,
      issues: locationIssues,
    },
    inventory,
    indexNow: { configured: isIndexNowConfigured() },
  };
}
